# Generated by Django 4.0.5 on 2022-07-02 11:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('eomployerId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('jobseekerId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=60)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='pic')),
                ('gender', models.CharField(max_length=10)),
                ('resume', cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('jobtypeId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('last_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=1000)),
                ('website', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiresapp.category')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiresapp.jobtype')),
            ],
        ),
    ]
