# Generated by Django 4.0.5 on 2022-07-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='current_opportunities',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employee_benefits',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience_years',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='professional_designation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='jobseeker_viewer',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='jobseeker_viewer',
            field=models.ManyToManyField(to='hiresapp.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
