# Generated by Django 4.0.5 on 2022-07-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Jobtype',
        ),
    ]
