# Generated by Django 4.0.5 on 2022-07-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
