# Generated by Django 4.0.5 on 2022-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0002_employerprofile_current_opportunities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='jobseeker_viewer',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='current_opportunities',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employee_benefits',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
