# Generated by Django 4.0.5 on 2022-07-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0002_remove_jobseekerprofile_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='jobseeker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hiresapp.jobseeker'),
        ),
    ]
