# Generated by Django 4.0.5 on 2022-07-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0002_jobseekerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='user',
        ),
    ]
