# Generated by Django 4.0.5 on 2022-07-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0003_remove_jobseekerprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
