# Generated by Django 4.0.5 on 2022-07-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0003_alter_jobseekerprofile_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hiresapp.employer'),
        ),
    ]
