# Generated by Django 4.0.5 on 2022-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0003_jobseekerprofile_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='name',
            field=models.CharField(default='Employers Name', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='fullname',
            field=models.CharField(default='Applicant Name', max_length=60),
        ),
    ]
