# Generated by Django 4.0.5 on 2022-07-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiresapp', '0004_alter_employerprofile_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
